parameters:
- name: dependsOn
  type: object
  default: []
- name: azureSubscription
  type: string
- name: environment
  type: string
- name: environmentName
  type: string
- name: environmentTag
  type: string


jobs:
- deployment: ValidateBicepAgainst${{ parameters.environmentName }}Environment
  dependsOn: ${{ parameters.dependsOn }}
  environment: ${{ parameters.environment }}

  strategy:
    runOnce:
      deploy:
        steps:
          - checkout: self

          - task: AzureCLI@2
            name: RunPreflightValidation
            inputs:
              azureSubscription: ${{ parameters.azureSubscription }}
              scriptType: 'pscore'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az deployment sub validate `
                  --name 'platformConnectivity${{ parameters.environmentName }}' `
                  --template-file $(Build.sourcesDirectory)/bicep/platform.bicep `
                  --location 'uksouth' `
                  --parameters @$(Build.sourcesDirectory)/params/platform.${{ parameters.environmentTag }}.json

          - task: AzureCLI@2
            name: RunWhatIfDeploy
            inputs:
              azureSubscription: ${{ parameters.azureSubscription }}
              scriptType: 'pscore'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az deployment sub what-if `
                  --name 'platformConnectivity${{ parameters.environmentName }}' `
                  --template-file $(Build.sourcesDirectory)/bicep/platform.bicep `
                  --location 'uksouth' `
                  --parameters @$(Build.sourcesDirectory)/params/platform.${{ parameters.environmentTag }}.json
