parameters:
- name: jobName
  type: string
  default: BicepEnvironmentValidation
- name: dependsOn
  type: object
  default: []
- name: azureSubscription
  type: string
- name: environment
  type: string

jobs:
- deployment: ${{ parameters.jobName }}
  dependsOn: ${{ parameters.dependsOn }}
  environment: 'platform-connectivity-${{ parameters.environment }}'

  strategy:
    runOnce:
      deploy:
        steps:
          - checkout: self

          - task: AzureCLI@2
            name: RunPreflightValidation
            inputs:
              azureSubscription: ${{ parameters.azureSubscription }}
              scriptType: 'pscore'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az deployment sub validate `
                  --template-file $(Build.sourcesDirectory)/bicep/platform.bicep `
                  --location 'uksouth' `
                  --parameters @$(Build.sourcesDirectory)/params/platform.${{ parameters.environment }}.json

          - task: AzureCLI@2
            name: RunWhatIfDeploy
            inputs:
              azureSubscription: ${{ parameters.azureSubscription }}
              scriptType: 'pscore'
              scriptLocation: 'inlineScript'
              inlineScript: |
                az deployment sub what-if `
                  --template-file $(Build.sourcesDirectory)/bicep/platform.bicep `
                  --location 'uksouth' `
                  --parameters @$(Build.sourcesDirectory)/params/platform.${{ parameters.environment }}.json
