parameters:
- name: azureSubscription
  type: string
- name: environment
  type: string
- name: environmentName
  type: string

stages: 
- stage: deploy_${{ parameters.environmentName }}_platform
  jobs:

  - deployment: deploy_${{ parameters.environmentName }}_platform_bicep
    environment: ${{ parameters.environment }}

    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self
            
            - task: AzureCLI@2
              displayName: deploy_${{ parameters.environmentName }}_platform_bicep
              inputs:
                azureSubscription: ${{ parameters.azureSubscription }}
                scriptType: 'pscore'
                scriptLocation: 'inlineScript'
                inlineScript: |
                  $config = (Get-Content ./params/platform.${{ parameters.environmentName }}.json | ConvertFrom-Json)

                  az deployment sub create `
                    --name 'platformConnectivity${{ parameters.environmentName }}' `
                    --template-file bicep/main.bicep `
                    --location $config.parameters.location.value `
                    --parameters @params/platform.${{ parameters.environmentName }}.json
