parameters:
- name: azureSubscription
  type: string
- name: environmentFriendlyName
  type: string
- name: environment
  type: string

stages: 
- stage: Deploy${{ parameters.environmentFriendlyName }}Platform
  jobs:

  - deployment: Deploy${{ parameters.environmentFriendlyName }}PlatformBicep
    environment: 'platform-connectivity-${{ parameters.environment }}'

    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self
            
            - task: AzureCLI@2
              displayName: Deploy${{ parameters.environmentFriendlyName }}PlatformBicep
              inputs:
                azureSubscription: ${{ parameters.azureSubscription }}
                scriptType: 'pscore'
                scriptLocation: 'inlineScript'
                inlineScript: |
                  az deployment sub create `
                    --template-file bicep/platform.bicep `
                    --location 'uksouth' `
                    --parameters @params/platform.${{ parameters.environment }}.json
