parameters:
- name: azureSubscription
  type: string
- name: environment
  type: string
- name: environmentName
  type: string
- name: environmentTag
  type: string

stages: 
- stage: Deploy${{ parameters.environmentName }}Platform
  jobs:

  - deployment: Deploy${{ parameters.environmentName }}PlatformBicep
    environment: ${{ parameters.environment }}

    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self
            
            - task: AzureCLI@2
              displayName: Deploy${{ parameters.environmentName }}PlatformBicep
              inputs:
                azureSubscription: ${{ parameters.azureSubscription }}
                scriptType: 'pscore'
                scriptLocation: 'inlineScript'
                inlineScript: |
                  az deployment sub create `
                    --template-file bicep/platform.bicep `
                    --location 'uksouth' `
                    --parameters @params/platform.${{ parameters.environmentTag }}.json
