trigger: none
pr: none

pool: 'Dedicated'

resources:
  pipelines:
  - pipeline: platform-connectivity.Validate
    source: platform-connectivity.Validate
    trigger:
      branches:
        include:
        - main

stages: 
- stage: DeployDevPlatform
  jobs:

  - deployment: DeployDevPlatformBicep
    environment: 'platform-connectivity-dev'

    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self
            
            - task: AzureCLI@2
              displayName: DeployDevPlatformBicep
              inputs:
                azureSubscription: 'spn-ado-Personal-Public-devtest'
                scriptType: 'pscore'
                scriptLocation: 'inlineScript'
                inlineScript: |
                  az deployment sub create `
                    --template-file bicep/platform.bicep `
                    --location 'uksouth' `
                    --parameters @params/platform.dev.json

- stage: DeployPrdPlatform
  jobs:

  - deployment: DeployPrdPlatformBicep
    environment: 'platform-connectivity-prd'

    strategy:
      runOnce:
        deploy:
          steps:
            - checkout: self
            
            - task: AzureCLI@2
              displayName: DeployPrdPlatformBicep
              inputs:
                azureSubscription: 'spn-ado-Personal-Public-platform-connectivity'
                scriptType: 'pscore'
                scriptLocation: 'inlineScript'
                inlineScript: |
                  az deployment sub create `
                    --template-file bicep/platform.bicep `
                    --location 'uksouth' `
                    --parameters @params/platform.prd.json