trigger: none
pr: none

pool: 'Dedicated'

resources:
  pipelines:
  - pipeline: platform-connectivity.Validate
    source: platform-connectivity.Validate
    trigger:
      branches:
        include:
        - main

stages: 
- stage: Validation
  jobs:
  - template: jobs/bicep-lint-code.yml@ado-pipeline-templates
    parameters: 
      jobName: 'BicepLinter'
      azureSubscription: 'spn-ado-Personal-Public-devtest'

  - template: templates/bicep-environment-validation.yml
    parameters:
      dependsOn: [BicepLinter]
      jobName: 'ValidateBicepAgainstPrdEnvironment'
      azureSubscription: 'spn-ado-Personal-Public-platform-connectivity'
      environment: 'prd'
      
- template: templates/deploy-environment.yml
  parameters:
    azureSubscription: 'spn-ado-Personal-Public-platform-connectivity'
    environmentFriendlyName: 'Prd'
    environment: 'prd'
