trigger:
  branches:
    include:
    - '*'
    exclude:
    - 'docs/*'

pr:
  branches:
    include:
    - '*'
    exclude:
    - 'docs/*'

pool: 'Dedicated'

resources:
  repositories:
    - repository: ado-pipeline-templates
      type: github
      name: frasermolyneux/ado-pipeline-templates
      endpoint: github.com_frasermolyneux

stages: 
- stage: Build
  jobs:
  - template: jobs/bicep-lint-code.yml@ado-pipeline-templates
    parameters: 
      jobName: 'BicepLinter'
      azureSubscription: 'spn-platform-connectivity-development'

  - template: templates/bicep-environment-validation.yml
    parameters:
      dependsOn: [BicepLinter]
      azureSubscription: 'spn-platform-connectivity-development'
      environment: 'platform-connectivity-Development'
      environmentName: 'Dev'
      environmentTag: 'dev'

  - template: templates/bicep-environment-validation.yml
    parameters:
      dependsOn: [BicepLinter]
      azureSubscription: 'spn-platform-connectivity-production'
      environment: 'platform-connectivity-Production'
      environmentName: 'Prd'
      environmentTag: 'prd'

- template: templates/deploy-environment.yml
  parameters:
    azureSubscription: 'spn-platform-connectivity-development'
    environment: 'platform-connectivity-Development'
    environmentName: 'Dev'
    environmentTag: 'dev'

- template: templates/deploy-environment.yml
  parameters:
    azureSubscription: 'spn-platform-connectivity-production'
    environment: 'platform-connectivity-Production'
    environmentName: 'Prd'
    environmentTag: 'prd'
